### ISSUE TITLE
Morse Code will crash flipper firmware

### ISSUE THREAD

**Issue by ryanthomp** [DarkFlippers/unleashed-firmware#219]
If I used the morse code tool for an extended period of time I find that it eventually crashes the flipper and forces it to restart.

**Comment by xMasterX** [comment]
Fixed in 022

**Comment by ryanthomp** [comment]
Bump, with 022 my flipper is still crashing on Morse Code application

**Comment by alevangel** [comment]
@ryanthomp How do you then fix this? After that my flipper doesn't mount anymore the SD Card.
I'm on 22 and faced same issue.
